kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: default-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: managed-premium-pvc
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azurefile-pvc
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azurefile-premium-pvc
spec:
  storageClassName: azurefile-premium
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
    - mountPath: "/mnt/default"
      name: default-volume
    - mountPath: "/mnt/managed-premium"
      name: managed-premium-volume
    - mountPath: "/mnt/azurefile"
      name: azurefile-volume
    - mountPath: "/mnt/azurefile-premium"
      name: azurefile-premium-volume
  volumes:
    - name: default-volume
      persistentVolumeClaim:
        claimName: default-pvc
    - name: managed-premium-volume
      persistentVolumeClaim:
        claimName: managed-premium-pvc
    - name: azurefile-volume
      persistentVolumeClaim:
        claimName: azurefile-pvc
    - name: azurefile-premium-volume
      persistentVolumeClaim:
        claimName: azurefile-premium-pvc