kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: noserverino
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
allowVolumeExpansion:  True
mountOptions:
  - noserverino
  - cache=strict
  - actimeo=30
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: loose30
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
allowVolumeExpansion:  True
mountOptions:
  - serverino
  - cache=loose
  - actimeo=30
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: loose0
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
allowVolumeExpansion:  True
mountOptions:
  - serverino
  - cache=loose
  - actimeo=0
reclaimPolicy: Delete
volumeBindingMode: Immediate