apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  resourceGroup: MC_NFSTest_ciscluster_westus  # optional, required only when storage account is not in the same resource group as your agent nodes
  storageAccount: nfs5150
  protocol: nfs